.\" Contact jules@baratoux.fr to correct errors or typos.
.TH script explore "26 October 2012" "1.0" "explore man page"
.SH NAME
explore \- Opens a window view for the specified folder or file
.SH SYNOPSIS
.B explore
[\fITARGET\fR]
.SH DESCRIPTION
Requires being in a \fBCygwin\fR environment.

Opens a new single-pane window, calling Windows \fBExplorer\fR. If a directory is passed as \fITARGET\fR, the folder is displayed. If a file is passed, the parent folder is displayed and this file is selected. Without any argument, the current directory is used.
.SH SEE ALSO
Microsoft Windows \fBExplorer\fR.
.SH BUGS
No known bugs.
.SH AUTHOR
Jules Baratoux (jules@baratoux.fr)
