#!/bin/bash
## mkemacs
##
## Made by jules baratoux
## Login   <barato_j@epitech.net>
##
## Started on  Mon Jul  2 15:31:38 2012 jules baratoux
## Last update Wed May 29 00:14:21 2013 jules baratoux
##
VERSION=3.2.4
# ┌───────────────────────────────────────────────────────────────────────────┐
# │                                 VARIABLES                                 │
# └───────────────────────────────────────────────────────────────────────────┘

# DIRS
EMACS_SHARE=~/Dropbox/share/emacs
EMACS_BAK=~/emacs.tgz
EMACS_D=~/.emacs.d
EMACS=~/.emacs

EMACS_LOG=$EMACS_SHARE/log.conf


# ┌───────────────────────────────────────────────────────────────────────────┐
# │                                 FUNCTIONS                                 │
# └───────────────────────────────────────────────────────────────────────────┘

fmt="ls --color -d"

function	main()
{
    touch $EMACS_D $EMACS								&&\
    tar -czf $EMACS_BAK $(basename $EMACS) $(basename $EMACS_D)				&&\
    echo `$fmt $EMACS` 'and' `$fmt $EMACS_D` 'saved in' `$fmt $EMACS_BAK`		&&\
											  \
    cp -n $EMACS_SHARE/default.el $EMACS_SHARE/$USER.el					&&\
    rm -Rf $EMACS $EMACS_D								&&\
    cp -Rs $EMACS_SHARE $EMACS_D							&&\
    echo `$fmt $EMACS_D` 'content created'						&&\
											  \
    ln -s $EMACS_D/$USER.el $EMACS  							&&\
    echo `$fmt $EMACS` 'linked to' `$fmt $EMACS_D/$USER.el`				&&\
											  \
    echo -e $USER:$VERSION:$(uname -o)"\t\t# "$(date '+%A, %d %B %Y') >> $EMACS_LOG
}


# ┌───────────────────────────────────────────────────────────────────────────┐
# │                                 EXECUTION                                 │
# └───────────────────────────────────────────────────────────────────────────┘

echo $(basename $0) $VERSION
cd $HOME && main | sed -e "s|$HOME/||g"

rm -Rf $EMACS_D/ac-comphist.dat
rm -Rf $EMACS_D/history
rm -Rf $EMACS_D/auto-save-list/

chmod --reference=$EMACS_D $EMACS_D/auto-complete-1.3.1/*
