.\" Manpage for mklink.
.\" Contact jules@baratoux.fr to correct errors or typos.
.TH script mklink "26 October 2012" "1.0" "mklink man page"
.SH NAME
mklink \- make NTFS links between files on Cygwin
.SH SYNOPSIS
.B mklink
[\fIOPTION\fR] \fITARGET\fR [\fILINK_NAME\fR]
.SH DESCRIPTION
Requires being in a \fBCygwin\fR environment.

Create a NTFS link to \fITARGET\fR with the name \fILINK_NAME\fR using windows \fBMKLINK\fR cmd. Make file hard links or directory junctions by default, symbolic link with \fB\-s\fR. When creating hard links, \fITARGET\fR must exist.
.SH OPTIONS
.TP
\fB\-s\fR
Creates a symbolic link instead of a hard link.
.SH SEE ALSO
Microsoft Windows \fBMKLINK\fR cmd.
.SH BUGS
No known bugs.
.SH AUTHOR
Jules Baratoux (jules@baratoux.fr)
