#!/bin/sh
## rclean
## 
## Made by jules baratoux
## Login   <barato_j@epitech.net>
## 
## Started on  Wed Jun  6 13:41:55 2012 jules baratoux
## Last update Thu Jun  7 18:34:09 2012 jules baratoux
##

## Recursive clean

DIR='.'

if [ ${1} ]
then
    DIR=${1}
fi

find -O3 ${DIR} -type f -name "*~" -o -name "#*#" -o -name ".#*" | sed 's/^/"/' | sed 's/$/&"/g' | xargs rm -fv ;