#!/bin/bash
## svn_st for svn
##
## Made by jules baratoux
## Login   <barato_j@epitech.net>
##
## Started on  Wed Jun  6 14:57:53 2012 jules baratoux
## Last update Fri Jun 21 22:53:56 2013 jules baratoux
##

/bin/echo "Status :"				&&\
svn st | grep -ve "TAGS" -oe "*.[od]"